mongodb.uri=mongodb://sithijahiripitiya16_db_user:sdVpaDn7AWlWHX5v@ac-9xbopuy-shard-00-00.vktmuhz.mongodb.net:27017,ac-9xbopuy-shard-00-01.vktmuhz.mongodb.net:27017,ac-9xbopuy-shard-00-02.vktmuhz.mongodb.net:27017/?ssl=true&replicaSet=atlas-gn0za3-shard-0&authSource=admin&appName=Cluster0
mongodb.database=GreenLoop
org.mongodb.driver.level=INFO